/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontDigital40.cpp                                     *
* Font:        Clarendon BT ONLY digital characters                  *
* Height:      40  AA2                                               *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  40                                           *
*                                                                    *
**********************************************************************/
#ifndef GUI_FontDigital40_H
#define GUI_FontDigital40_H

//-----------------------------------------------------------------------------
#include "GUI_Type.h"
//-----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif
//=============================================================================
// 全局变量
//---------------------------------------------------------------------------
// 34x40 Digital AA2
extern const GUI_FONT GUI_FontDigital40;

#define GUI_FONT_AA2_DIGITAL40 (&GUI_FontDigital40)
//---------------------------------------------------------------------------
#ifdef __cplusplus
}
#endif
//---------------------------------------------------------------------------
#endif //GUI_FontDigital40_H
