/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontClarendonBT32.cpp                                 *
* Font:        Clarendon BT Digital and capital characters           *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
*                                                                    *
**********************************************************************/
#ifndef GUI_FontClarendonBT32_H
#define GUI_FontClarendonBT32_H

//-----------------------------------------------------------------------------
#include "GUI_Type.h"
//-----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif
//=============================================================================
// 全局变量
//---------------------------------------------------------------------------
// 12x24 ASCII
extern const GUI_FONT GUI_FontDIGCAP22;

#define GUI_FONT_DIGCAP22 (&GUI_FontDIGCAP22)
//---------------------------------------------------------------------------
#ifdef __cplusplus
}
#endif
//---------------------------------------------------------------------------
#endif //GUI_FontClarendonBT32_H
