/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontDigital44B.cpp                                    *
* Font:        Hei AA2                                               *
* Height:      44                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  44                                           *
*                                                                    *
**********************************************************************/
#ifndef GUI_FontDigital44B_H
#define GUI_FontDigital44B_H

//-----------------------------------------------------------------------------
#include "GUI_Type.h"
//-----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif
//=============================================================================
// 全局变量
//---------------------------------------------------------------------------
// 32x44 Digital-Bold  AA2
extern const GUI_FONT GUI_FontDigital44B;

#define GUI_FONT_AA2_DIGITAL44B (&GUI_FontDigital44B)
//---------------------------------------------------------------------------
#ifdef __cplusplus
}
#endif
//---------------------------------------------------------------------------
#endif //GUI_FontDigital44B_H
