/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontDigital32B.h                                      *
* Font:        Adobe Gothic Std Bold AA2                             *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
*                                                                    *
**********************************************************************/
#ifndef GUI_FontDigital32B_H
#define GUI_FontDigital32B_H

//-----------------------------------------------------------------------------
#include "GUI_Type.h"
//-----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif
//=============================================================================
// 全局变量
//---------------------------------------------------------------------------
// 23x32 ASCII AA2
extern const GUI_FONT GUI_FontDigital32B;

#define GUI_FONT_AA2_DIGITAL32B (&GUI_FontDigital32B)
//---------------------------------------------------------------------------
#ifdef __cplusplus
}
#endif
//---------------------------------------------------------------------------
#endif //GUI_FontDigital32B_H
